<!doctype html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">
    <title>FizzBuzz</title>
    <!-- Twitter Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/"><em>Fizz</em><strong>Buzz</strong></a>
            </div>
            <ul class="nav navbar-nav">
                <?php $sections = $this->container->get('Menu')->getSections(); ?>
                
                <?php foreach($sections as $section ): ?>
                    <?php 
                        $router= $this->container->get('Router');
                        $route_url = $router->generate('section', array(
                            'slug' => $section['slug']
                        )); 
                    ?>
                    <li><a href="<?php echo $route_url; ?>"><?php echo $section['title']; ?></a></li>
                <?php endforeach; ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/phpinfo">phpinfo</a></li>
            </ul>
        </div>
    </nav>
