<?php
// autoload.php @generated by Composer

if (!defined(APP_ENV)) {
    define('APP_ENV', 'development');
}

require_once '../vendor/composer/autoload_real.php';

return ComposerAutoloaderInit017d81e3b7956f99cb2ad49f016d91fc::getLoader();
