<?php include(__DIR__.'/inc/header.phtml'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <p class="lead">
                Answering
                <a href="http://c2.com/cgi/wiki?FizzBuzzTest" onclick="window.open(this.href)">
                    niche, premeditated interview questions
                </a>
                in pseudo code is boring.
                <br>
                <small>
                    And it doesn't offer us much useful insight into your
                    effectiveness as a developer.
                </small>
            </p>
            <hr>
            <p class="lead">
                This technical assessment consists of a small php application with
                some issues that need resolving.
                <br>
                <small>
                    It's built using some components that you've never heard of
                    because we want to see how you approach a codebase that's
                    different to your CMS/Framework/Tool of choice.
                </small>
            </p>
            <hr>
            <h2>Instructions</h2>
            <p>
                <strong>1.</strong>
                Fork the repository from here:
                <a href="https://github.com/joegreen88/phptest">
                    https://github.com/joegreen88/phptest
                </a>
            </p>
            <p>
                <strong>2.</strong>
                Get it running on your own local / development environment
                (if you are reading this page in the browser then you have probably already come this far).
            </p>
            <p>
                <strong>3.</strong>
                Have a look at the <a href="/section/tasks">tasks</a> and
                start hacking away.
                <em>
                    Be sure to commit your changes and push them up to your fork.
                </em>
            </p>
            <p>
                <strong>4.</strong>
                Once you've had enough or run out of tasks then
                open a pull request from your fork back into the master branch
                of the main repo.
                <br>
                <strong>
                    Feel free to add feedback, comments or suggestions to your PR.
                </strong>
            </p>
            <hr>
            <h3>Guidelines</h3>
            <ul>
                <li>Stick to any code conventions that are apparent in the code.</li>
                <li>Stick to php, mysql, composer, apache for this assessment.</li>
                <li>Feel free to add composer dependencies if you think it's justified.</li>
                <li>
                    You may not find time to complete all of the tasks,
                    which is fine, just indicate in your PR which tasks are
                    complete and how much time has been spent.
                </li>
                <li>
                    You may decide that it's not feasible to complete a task,
                    in this case please indicate why on the PR.
                </li>
            </ul>
            <hr>
            <p class="lead">
                Best of luck!
            </p>
        </div>
    </div>
</div>

<?php include(__DIR__.'/inc/footer.phtml'); ?>
